service: cadastro-em-batch
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  simulandoUploadDoCSV:
    handler: index.simulandoUploadDoCSV
    events:
      - httpApi:
          path: /alunos/batch
          method: post

  cadastrarAlunos:
    handler: index.cadastrarAlunos
    events:
      - s3:
          bucket: alunos-csv-local
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv

plugins:
  - serverless-offline
  - serverless-s3-local
